[2021-08-07 19:15:27,766] {scheduler_job.py:182} INFO - Started process (PID=25) to work on /opt/airflow/dags/tutorial.py
[2021-08-07 19:15:27,767] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/tutorial.py for tasks to queue
[2021-08-07 19:15:27,769] {logging_mixin.py:104} INFO - [2021-08-07 19:15:27,769] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/tutorial.py
[2021-08-07 19:15:28,502] {logging_mixin.py:104} INFO - [2021-08-07 19:15:28,500] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/tutorial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tutorial.py", line 43, in <module>
    conn = BaseHook.get_connection('aws_default')
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `aws_default` isn't defined
[2021-08-07 19:15:28,502] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/tutorial.py
[2021-08-07 19:15:28,516] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/tutorial.py took 0.757 seconds
[2021-08-07 19:16:27,656] {scheduler_job.py:182} INFO - Started process (PID=348) to work on /opt/airflow/dags/tutorial.py
[2021-08-07 19:16:27,658] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/tutorial.py for tasks to queue
[2021-08-07 19:16:27,658] {logging_mixin.py:104} INFO - [2021-08-07 19:16:27,658] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/tutorial.py
[2021-08-07 19:16:27,813] {logging_mixin.py:104} INFO - [2021-08-07 19:16:27,812] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/tutorial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tutorial.py", line 43, in <module>
    conn = BaseHook.get_connection('aws_default')
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `aws_default` isn't defined
[2021-08-07 19:16:27,814] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/tutorial.py
[2021-08-07 19:16:27,821] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/tutorial.py took 0.168 seconds
[2021-08-07 19:16:57,915] {scheduler_job.py:182} INFO - Started process (PID=402) to work on /opt/airflow/dags/tutorial.py
[2021-08-07 19:16:57,916] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/tutorial.py for tasks to queue
[2021-08-07 19:16:57,917] {logging_mixin.py:104} INFO - [2021-08-07 19:16:57,917] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/tutorial.py
[2021-08-07 19:16:58,073] {logging_mixin.py:104} INFO - [2021-08-07 19:16:58,072] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/tutorial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tutorial.py", line 43, in <module>
    conn = BaseHook.get_connection('aws_default')
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `aws_default` isn't defined
[2021-08-07 19:16:58,074] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/tutorial.py
[2021-08-07 19:16:58,079] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/tutorial.py took 0.167 seconds
[2021-08-07 19:17:29,098] {scheduler_job.py:182} INFO - Started process (PID=465) to work on /opt/airflow/dags/tutorial.py
[2021-08-07 19:17:29,099] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/tutorial.py for tasks to queue
[2021-08-07 19:17:29,100] {logging_mixin.py:104} INFO - [2021-08-07 19:17:29,100] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/tutorial.py
[2021-08-07 19:17:29,378] {logging_mixin.py:104} INFO - [2021-08-07 19:17:29,376] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/tutorial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tutorial.py", line 43, in <module>
    conn = BaseHook.get_connection('aws_default')
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `aws_default` isn't defined
[2021-08-07 19:17:29,379] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/tutorial.py
[2021-08-07 19:17:29,391] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/tutorial.py took 0.300 seconds
[2021-08-07 19:18:00,303] {scheduler_job.py:182} INFO - Started process (PID=521) to work on /opt/airflow/dags/tutorial.py
[2021-08-07 19:18:00,313] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/tutorial.py for tasks to queue
[2021-08-07 19:18:00,315] {logging_mixin.py:104} INFO - [2021-08-07 19:18:00,315] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/tutorial.py
[2021-08-07 19:18:00,494] {logging_mixin.py:104} INFO - [2021-08-07 19:18:00,493] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/tutorial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tutorial.py", line 43, in <module>
    conn = BaseHook.get_connection('aws_default')
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `aws_default` isn't defined
[2021-08-07 19:18:00,495] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/tutorial.py
[2021-08-07 19:18:00,502] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/tutorial.py took 0.202 seconds
[2021-08-07 19:18:30,583] {scheduler_job.py:182} INFO - Started process (PID=575) to work on /opt/airflow/dags/tutorial.py
[2021-08-07 19:18:30,585] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/tutorial.py for tasks to queue
[2021-08-07 19:18:30,586] {logging_mixin.py:104} INFO - [2021-08-07 19:18:30,585] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/tutorial.py
[2021-08-07 19:18:30,706] {logging_mixin.py:104} INFO - [2021-08-07 19:18:30,705] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/tutorial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tutorial.py", line 43, in <module>
    conn = BaseHook.get_connection('aws_default')
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `aws_default` isn't defined
[2021-08-07 19:18:30,706] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/tutorial.py
[2021-08-07 19:18:30,712] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/tutorial.py took 0.133 seconds
[2021-08-07 19:19:00,946] {scheduler_job.py:182} INFO - Started process (PID=640) to work on /opt/airflow/dags/tutorial.py
[2021-08-07 19:19:00,947] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/tutorial.py for tasks to queue
[2021-08-07 19:19:00,948] {logging_mixin.py:104} INFO - [2021-08-07 19:19:00,948] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/tutorial.py
[2021-08-07 19:19:01,084] {logging_mixin.py:104} INFO - [2021-08-07 19:19:01,083] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/tutorial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tutorial.py", line 43, in <module>
    conn = BaseHook.get_connection('aws_default')
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `aws_default` isn't defined
[2021-08-07 19:19:01,085] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/tutorial.py
[2021-08-07 19:19:01,092] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/tutorial.py took 0.151 seconds
[2021-08-07 19:19:31,149] {scheduler_job.py:182} INFO - Started process (PID=693) to work on /opt/airflow/dags/tutorial.py
[2021-08-07 19:19:31,150] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/tutorial.py for tasks to queue
[2021-08-07 19:19:31,150] {logging_mixin.py:104} INFO - [2021-08-07 19:19:31,150] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/tutorial.py
[2021-08-07 19:19:31,311] {logging_mixin.py:104} INFO - [2021-08-07 19:19:31,309] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/tutorial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tutorial.py", line 43, in <module>
    conn = BaseHook.get_connection('aws_default')
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `aws_default` isn't defined
[2021-08-07 19:19:31,312] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/tutorial.py
[2021-08-07 19:19:31,319] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/tutorial.py took 0.174 seconds
[2021-08-07 19:20:01,375] {scheduler_job.py:182} INFO - Started process (PID=760) to work on /opt/airflow/dags/tutorial.py
[2021-08-07 19:20:01,377] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/tutorial.py for tasks to queue
[2021-08-07 19:20:01,378] {logging_mixin.py:104} INFO - [2021-08-07 19:20:01,378] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/tutorial.py
[2021-08-07 19:20:01,533] {logging_mixin.py:104} INFO - [2021-08-07 19:20:01,532] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/tutorial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tutorial.py", line 43, in <module>
    conn = BaseHook.get_connection('aws_default')
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `aws_default` isn't defined
[2021-08-07 19:20:01,534] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/tutorial.py
[2021-08-07 19:20:01,540] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/tutorial.py took 0.169 seconds
[2021-08-07 19:20:31,644] {scheduler_job.py:182} INFO - Started process (PID=814) to work on /opt/airflow/dags/tutorial.py
[2021-08-07 19:20:31,645] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/tutorial.py for tasks to queue
[2021-08-07 19:20:31,646] {logging_mixin.py:104} INFO - [2021-08-07 19:20:31,646] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/tutorial.py
[2021-08-07 19:20:31,812] {logging_mixin.py:104} INFO - [2021-08-07 19:20:31,811] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/tutorial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tutorial.py", line 43, in <module>
    conn = BaseHook.get_connection('aws_default')
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `aws_default` isn't defined
[2021-08-07 19:20:31,812] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/tutorial.py
[2021-08-07 19:20:31,820] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/tutorial.py took 0.180 seconds
[2021-08-07 19:21:01,854] {scheduler_job.py:182} INFO - Started process (PID=877) to work on /opt/airflow/dags/tutorial.py
[2021-08-07 19:21:01,856] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/tutorial.py for tasks to queue
[2021-08-07 19:21:01,857] {logging_mixin.py:104} INFO - [2021-08-07 19:21:01,857] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/tutorial.py
[2021-08-07 19:21:01,988] {logging_mixin.py:104} INFO - [2021-08-07 19:21:01,987] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/tutorial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tutorial.py", line 43, in <module>
    conn = BaseHook.get_connection('aws_default')
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `aws_default` isn't defined
[2021-08-07 19:21:01,989] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/tutorial.py
[2021-08-07 19:21:01,998] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/tutorial.py took 0.148 seconds
[2021-08-07 19:21:32,033] {scheduler_job.py:182} INFO - Started process (PID=931) to work on /opt/airflow/dags/tutorial.py
[2021-08-07 19:21:32,034] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/tutorial.py for tasks to queue
[2021-08-07 19:21:32,035] {logging_mixin.py:104} INFO - [2021-08-07 19:21:32,034] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/tutorial.py
[2021-08-07 19:21:32,154] {logging_mixin.py:104} INFO - [2021-08-07 19:21:32,153] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/tutorial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tutorial.py", line 43, in <module>
    conn = BaseHook.get_connection('aws_default')
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `aws_default` isn't defined
[2021-08-07 19:21:32,154] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/tutorial.py
[2021-08-07 19:21:32,161] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/tutorial.py took 0.130 seconds
[2021-08-07 19:22:02,231] {scheduler_job.py:182} INFO - Started process (PID=994) to work on /opt/airflow/dags/tutorial.py
[2021-08-07 19:22:02,232] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/tutorial.py for tasks to queue
[2021-08-07 19:22:02,233] {logging_mixin.py:104} INFO - [2021-08-07 19:22:02,233] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/tutorial.py
[2021-08-07 19:22:02,358] {logging_mixin.py:104} INFO - [2021-08-07 19:22:02,358] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/tutorial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tutorial.py", line 43, in <module>
    conn = BaseHook.get_connection('aws_default')
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `aws_default` isn't defined
[2021-08-07 19:22:02,359] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/tutorial.py
[2021-08-07 19:22:02,366] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/tutorial.py took 0.138 seconds
[2021-08-07 19:22:46,854] {scheduler_job.py:182} INFO - Started process (PID=1029) to work on /opt/airflow/dags/tutorial.py
[2021-08-07 19:22:46,857] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/tutorial.py for tasks to queue
[2021-08-07 19:22:46,860] {logging_mixin.py:104} INFO - [2021-08-07 19:22:46,858] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/tutorial.py
[2021-08-07 19:22:47,075] {logging_mixin.py:104} INFO - [2021-08-07 19:22:47,074] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/tutorial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tutorial.py", line 43, in <module>
    conn = BaseHook.get_connection('aws_default')
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `aws_default` isn't defined
[2021-08-07 19:22:47,075] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/tutorial.py
[2021-08-07 19:22:47,081] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/tutorial.py took 0.235 seconds
[2021-08-07 19:23:17,588] {scheduler_job.py:182} INFO - Started process (PID=1093) to work on /opt/airflow/dags/tutorial.py
[2021-08-07 19:23:17,589] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/tutorial.py for tasks to queue
[2021-08-07 19:23:17,589] {logging_mixin.py:104} INFO - [2021-08-07 19:23:17,589] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/tutorial.py
[2021-08-07 19:23:17,678] {logging_mixin.py:104} INFO - [2021-08-07 19:23:17,677] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/tutorial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tutorial.py", line 43, in <module>
    conn = BaseHook.get_connection('aws_default')
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `aws_default` isn't defined
[2021-08-07 19:23:17,678] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/tutorial.py
[2021-08-07 19:23:17,684] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/tutorial.py took 0.098 seconds
[2021-08-07 19:23:47,766] {scheduler_job.py:182} INFO - Started process (PID=1154) to work on /opt/airflow/dags/tutorial.py
[2021-08-07 19:23:47,768] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/tutorial.py for tasks to queue
[2021-08-07 19:23:47,769] {logging_mixin.py:104} INFO - [2021-08-07 19:23:47,769] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/tutorial.py
[2021-08-07 19:23:47,915] {logging_mixin.py:104} INFO - [2021-08-07 19:23:47,914] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/tutorial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tutorial.py", line 43, in <module>
    conn = BaseHook.get_connection('aws_default')
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `aws_default` isn't defined
[2021-08-07 19:23:47,915] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/tutorial.py
[2021-08-07 19:23:47,924] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/tutorial.py took 0.162 seconds
[2021-08-07 19:24:18,698] {scheduler_job.py:182} INFO - Started process (PID=1207) to work on /opt/airflow/dags/tutorial.py
[2021-08-07 19:24:18,699] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/tutorial.py for tasks to queue
[2021-08-07 19:24:18,699] {logging_mixin.py:104} INFO - [2021-08-07 19:24:18,699] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/tutorial.py
[2021-08-07 19:24:18,788] {logging_mixin.py:104} INFO - [2021-08-07 19:24:18,787] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/tutorial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tutorial.py", line 43, in <module>
    conn = BaseHook.get_connection('aws_default')
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `aws_default` isn't defined
[2021-08-07 19:24:18,789] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/tutorial.py
[2021-08-07 19:24:18,795] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/tutorial.py took 0.100 seconds
[2021-08-07 19:24:49,509] {scheduler_job.py:182} INFO - Started process (PID=1271) to work on /opt/airflow/dags/tutorial.py
[2021-08-07 19:24:49,510] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/tutorial.py for tasks to queue
[2021-08-07 19:24:49,511] {logging_mixin.py:104} INFO - [2021-08-07 19:24:49,511] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/tutorial.py
[2021-08-07 19:24:49,597] {logging_mixin.py:104} INFO - [2021-08-07 19:24:49,596] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/tutorial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tutorial.py", line 43, in <module>
    conn = BaseHook.get_connection('aws_default')
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 381, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `aws_default` isn't defined
[2021-08-07 19:24:49,597] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/tutorial.py
[2021-08-07 19:24:49,603] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/tutorial.py took 0.096 seconds
