[2021-10-21 18:48:37,125] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: Fire_Incidents.Check_credentials 2021-10-20T00:00:00+00:00 [queued]>
[2021-10-21 18:48:37,140] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: Fire_Incidents.Check_credentials 2021-10-20T00:00:00+00:00 [queued]>
[2021-10-21 18:48:37,140] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-10-21 18:48:37,141] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-10-21 18:48:37,141] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-10-21 18:48:37,148] {taskinstance.py:1089} INFO - Executing <Task(PythonOperator): Check_credentials> on 2021-10-20T00:00:00+00:00
[2021-10-21 18:48:37,154] {standard_task_runner.py:52} INFO - Started process 51 to run task
[2021-10-21 18:48:37,157] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fire_Incidents', 'Check_credentials', '2021-10-20T00:00:00+00:00', '--job-id', '4', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/tutorial.py', '--cfg-path', '/tmp/tmpismw5udi', '--error-file', '/tmp/tmpi3n_i857']
[2021-10-21 18:48:37,158] {standard_task_runner.py:77} INFO - Job 4: Subtask Check_credentials
[2021-10-21 18:48:37,192] {logging_mixin.py:104} INFO - Running <TaskInstance: Fire_Incidents.Check_credentials 2021-10-20T00:00:00+00:00 [running]> on host 8ad12bb33883
[2021-10-21 18:48:37,225] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Fire_Incidents
AIRFLOW_CTX_TASK_ID=Check_credentials
AIRFLOW_CTX_EXECUTION_DATE=2021-10-20T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-20T00:00:00+00:00
[2021-10-21 18:48:37,226] {logging_mixin.py:104} INFO - The Connection is:
[2021-10-21 18:48:37,226] {logging_mixin.py:104} INFO - {'region': 'us-west-2', 'access_token': 'FwoGZXIvYXdzEGoaDJReBSrOlfC09PeS7SKGAZYj8TJ17+aoC63as7iG5hoBR6sd977vDzKvgWTMf7J1mFWT3CBpgmPbT2hsPhjLMqX6qepk+EEKQgPTWaApYSUDed6XjBkZHt1mKVAH8TpjdS9+8MgDcEZJbapU8wizUZPzy0Yer2ot+23uFsHEWmWBJ9Oaf/mtLOmzdf/1uz3TsCOcbXRIKMvhwosGMij2XzeTshWnu45hR8qAGzfLMl4Zqr9PrjEI3oI7wOhJJWhks7mxcYAB'}
[2021-10-21 18:48:37,227] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tutorial.py", line 88, in check
    print(info["region_name"])
KeyError: 'region_name'
[2021-10-21 18:48:37,229] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=Fire_Incidents, task_id=Check_credentials, execution_date=20211020T000000, start_date=20211021T184837, end_date=20211021T184837
[2021-10-21 18:48:37,291] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-10-21 19:04:54,149] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: Fire_Incidents.Check_credentials 2021-10-20T00:00:00+00:00 [queued]>
[2021-10-21 19:04:54,165] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: Fire_Incidents.Check_credentials 2021-10-20T00:00:00+00:00 [queued]>
[2021-10-21 19:04:54,165] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-10-21 19:04:54,165] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-10-21 19:04:54,165] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-10-21 19:04:54,174] {taskinstance.py:1089} INFO - Executing <Task(PythonOperator): Check_credentials> on 2021-10-20T00:00:00+00:00
[2021-10-21 19:04:54,180] {standard_task_runner.py:52} INFO - Started process 52 to run task
[2021-10-21 19:04:54,183] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fire_Incidents', 'Check_credentials', '2021-10-20T00:00:00+00:00', '--job-id', '3', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/fire_incidents_glue.py', '--cfg-path', '/tmp/tmp38m9_gd3', '--error-file', '/tmp/tmp5tvst_t3']
[2021-10-21 19:04:54,183] {standard_task_runner.py:77} INFO - Job 3: Subtask Check_credentials
[2021-10-21 19:04:54,219] {logging_mixin.py:104} INFO - Running <TaskInstance: Fire_Incidents.Check_credentials 2021-10-20T00:00:00+00:00 [running]> on host 9da1750f0b7f
[2021-10-21 19:04:54,255] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Fire_Incidents
AIRFLOW_CTX_TASK_ID=Check_credentials
AIRFLOW_CTX_EXECUTION_DATE=2021-10-20T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-20T00:00:00+00:00
[2021-10-21 19:04:54,256] {logging_mixin.py:104} INFO - The Connection is:
[2021-10-21 19:04:54,257] {logging_mixin.py:104} INFO - {'region_name': 'us-west-2', 'aws_session_token': 'FwoGZXIvYXdzEGoaDJReBSrOlfC09PeS7SKGAZYj8TJ17+aoC63as7iG5hoBR6sd977vDzKvgWTMf7J1mFWT3CBpgmPbT2hsPhjLMqX6qepk+EEKQgPTWaApYSUDed6XjBkZHt1mKVAH8TpjdS9+8MgDcEZJbapU8wizUZPzy0Yer2ot+23uFsHEWmWBJ9Oaf/mtLOmzdf/1uz3TsCOcbXRIKMvhwosGMij2XzeTshWnu45hR8qAGzfLMl4Zqr9PrjEI3oI7wOhJJWhks7mxcYAB'}
[2021-10-21 19:04:54,257] {logging_mixin.py:104} INFO - us-west-2
[2021-10-21 19:04:54,257] {logging_mixin.py:104} INFO - FwoGZXIvYXdzEGoaDJReBSrOlfC09PeS7SKGAZYj8TJ17+aoC63as7iG5hoBR6sd977vDzKvgWTMf7J1mFWT3CBpgmPbT2hsPhjLMqX6qepk+EEKQgPTWaApYSUDed6XjBkZHt1mKVAH8TpjdS9+8MgDcEZJbapU8wizUZPzy0Yer2ot+23uFsHEWmWBJ9Oaf/mtLOmzdf/1uz3TsCOcbXRIKMvhwosGMij2XzeTshWnu45hR8qAGzfLMl4Zqr9PrjEI3oI7wOhJJWhks7mxcYAB
[2021-10-21 19:04:54,257] {python.py:118} INFO - Done. Returned value was: None
[2021-10-21 19:04:54,267] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=Fire_Incidents, task_id=Check_credentials, execution_date=20211020T000000, start_date=20211021T190454, end_date=20211021T190454
[2021-10-21 19:04:54,294] {taskinstance.py:1246} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-10-21 19:04:54,316] {local_task_job.py:146} INFO - Task exited with return code 0
